### ISSUE TITLE
Backing up content from Guestbook

### ISSUE THREAD

**Issue by mgaved** [mazi-project/mazi-board#1]
Future versions of the Guestbook to include documentation (guidance) on how to back up existing content for export to another unpopulated Guestbook. The Guestbook might be used off-line somewhere and the organisers of an event may wish to copy content out to another installation, or a web based version, or into another format to allow data analysis.

**Comment by panosnethood** [comment]
same as #5. It is already addressed in the latest version.

**Comment by panosnethood** [comment]
Closed this by mistake. I thought it was the same as #4. Re-opening it. I think this is for later ...

**Comment by deckspace** [comment]
Hi Panos are you saying that there has been a export config option added since v1.5?

**Comment by panosnethood** [comment]
I got confused a little. There is an export config for the portal, not the guestbook. And the above issue is about content not config. Sorry for adding to the confusion. I messed things a little but we will all learn. I like a lot the github Issues functionality :-)

**Comment by haniavis** [comment]
This is a reality since v1.8.5
