### ISSUE TITLE
Add maximum file size on submission page

### ISSUE THREAD

**Issue by mgaved** [mazi-project/mazi-board#11]
On the post submission page, near the button "Attach Image", indicate the maximum file size allowed (e.g. "max file size 2Mb"). 

This will reduce user frustration by indicating they are expected to check the size of the file they are uploading before attempting to load any image size. 

It would be great if this file size was dynamically generated by reading from /var/www/html/mazi-board/src/node/config.js so if the administrator manually changes the maximum allowed file size that can be uploaded, this user facing message also changes to the correct number.

**Comment by haniavis** [comment]
This is fixed in v2.3
