### ISSUE TITLE
Easy configuration of guestbook?

### ISSUE THREAD

**Issue by andreasunteidig** [mazi-project/mazi-board#14]
I just learned from James how to customize background image, texts and tags in Terminal. This is way too difficult for many of the community partners, but adjustability is vital. A script for adjusting these things in the dashboard would be tremendously helpful.

**Comment by mgaved** [comment]
This picks up on issue #10 (request for commenting the css file) but I like the idea of a dashboard tool as well as a commented css file.

**Comment by haniavis** [comment]
This is now integrated in version 2 of the toolkit
