### ISSUE TITLE
ready for V2, open issues: error message, admin password, css editing

### ISSUE THREAD

**Issue by deckspace** [mazi-project/mazi-board#16]
Just a comment or two on the new guest book config tool.

Great to be able to moderate the messages and a set background image, how can we remove the image and set a background colour? 

Now we can add and edit tags and the welcome message here is also great, though we also need to be able to edit all the text elements that appear in the interface. 

What about the CSS? Our bigest problem has been in editing the text colours in all the various situations as there is not a global for the 'message' and ' name' for instance. So once we can edit the text fields we will also like to edit the colours to make them more readable

If the message form is not completed with 'message' and 'name' before posting we see an error message [HTTP-ERROR: Submission validation failed] which doesn't help the confused user. It would be more useful if there was a helpful message here instead eg.

'Please write a message and add your name before posting'

Can we please also set the admin password for guestbook here?

I feel these issues are in need of consideration before launch of V2, will you have time to make these additions/changes?

**Comment by panosnethood** [comment]
Agreed for all the text elements ("what do you have to say", "Your name", "Image", "Submit") and admin password. I think these are the most important.

Error message used to work and I guess it is very easy to fix.

For background colour there are workarounds (uploading a jpg file with the colour of choice) and for css perhaps the easiest would be to allow to edit the whole css file, nicely commented, on a web form?

**Comment by mgaved** [comment]
+1 agree that the css should commented to allow easy editing

**Comment by haniavis** [comment]
This can be closed after the update of Guestbook in v2.3.

Please have in mind that we are working on merging the admin credentials of the MAZI Portal and Guestbook.
