### ISSUE TITLE
suggestion: identify current background image in admin interface, and default image size

### ISSUE THREAD

**Issue by mgaved** [mazi-project/mazi-board#19]
(v2.3.1): In the current Guestbook admin interface (http://portal.mazizone.eu/admin_guestbook) , there is an option to change the Background image

Two suggestions for additions to functionality:

(1) indicate the size of the default background images (pixels) so somebody generating a new image knows what will fit well. Either use the Info button or the body text to show this information

(2) indicate the file name of the current background image. I changed the image to my own (and forgot!) and in the admin interface it notes (Choose File) no file chosen. Perhaps the name of the currently used file could be indicated. This would give the administrator a visual reminder that they've changed the default image, and what they are currently using.

Thanks!
Mark

**Comment by mgaved** [comment]
This issue still live in v2.6 (released Nov. 2018): would be great to solve it! thanks!

**Comment by haniavis** [comment]
Hi, thanks for reporting this.

Since v3, the current image is shown in the Guestbook admin.
