### ISSUE TITLE
Guestbook not working in Internet Explorer?

### ISSUE THREAD

**Issue by mgaved** [mazi-project/mazi-board#22]
Does Guestbook have an issue working in Internet Explorer? I have tried using Win7 / IE11 and I get a blank page when clicking on the guestbook. The other applications on the MAZIzone seem to work (I can get to the main applications page, NextCloud works, Etherpad works).

thanks!

We are going to test this in a community setting in sub-Saharan Africa where I cannot be sure of the browsers people are using and I won't be able to ask them to download and configure an alternative browser. It might be some or all of them are using Internet Explorer.

**Comment by haniavis** [comment]
Guestbook is working in Internet Explorer as in all browsers... 

Your guestbook instance is probably broken due to an update you did in the development channel.

Can you try again to update in the stable channel and verify?

**Comment by mgaved** [comment]
Thanks for the feedback. This was experienced on stable branch v2.5.3 on Win7 / IE11 on two different university laptops. It did work on Chrome browser on both these laptops. We will try again next week.
