### ISSUE TITLE
saving of configuration

### ISSUE THREAD

**Issue by deckspace** [mazi-project/mazi-board#4]
We need to able to save current configuration to a local file , usb or network storage iscsi?
an then recover this configuration for use in another setting.

**Comment by panosnethood** [comment]
good point, and it is already implemented in the newest version to be made available soon.

**Comment by panosnethood** [comment]
@haniavis I assigned you just to be sure that this is correct since I didn't try it myself yet. But also to play a little with the github features :-)

**Comment by panosnethood** [comment]
Actually, I am confused because I thought that this is for the "portal" while this is the "mazi-board" issues. Would you like to have the same feature (saving configuration) for the mazi-board as well?

**Comment by panosnethood** [comment]
I am re-opening this since it is not clear if it refers to the portal or the mazi-board aka guestbook.

**Comment by deckspace** [comment]
we need to be able to save all the configurations for all the apps installed and the overall interface. I think we should go further and encourage sharing of configurations.. not least as start points for others to test out if they can't imagine what can be done.

**Comment by mgaved** [comment]
I agree with James - it would be good to be able to easily share alternative configurations between communities using mazizones. At this stage, I would be interested as part of the CreekNet team to be able to try out the mazizone configurations being used in different pilots to see if we can learn from their approaches.  (p.s. how do I add a label in this tool? !  :-) )

**Comment by deckspace** [comment]
I am adding this here again as the earlier notes vanished. Regards import and export of toolbox configuration, we were able to setup our installation and export from the admin interface and then save that config to an local/external storage, great. However it did not record the appearance settings which has a separate option to save a 'theme' but does not offer export in the same way as the rest of the config, so is not portable.

**Comment by panosnethood** [comment]
Hi, I think this is meant to be the same issue as issue 6, at the portal repository: https://github.com/mazi-project/portal/issues/6

**Comment by deckspace** [comment]
oh hell yes.. so it is

**Comment by haniavis** [comment]
You can now export the configuration of the Guestbook application (message, background image, tags etc.), together with its content (posts, photos, comments etc.), using the "Application Snapshots" section in the Export/Import menu.
