### ISSUE TITLE
mazi-board file upload size

### ISSUE THREAD

**Issue by deckspace** [mazi-project/mazi-board#5]
Trying to modify the upload size in the node/config but am not sure what needs to change in this string
maxFileSize: 1024*1024*2, //in bytes
what do these element refer to?

when I set       maxFileSize: 10240*10240*2, //in bytes ?
I still get asked to fill in both the Name and Text fields,
now working after reboot.

I do hope these configuration setting are included in a wysiwyg config interface

**Comment by panosnethood** [comment]
Hi, you say "now working after reboot". What do you refer to? Did you successfully manage to change the maxFileSize?

**Comment by deckspace** [comment]
yes but I don't understand the parameters I am changing..
the rendering of the string here is different to that I posted. ...
maxFileSize: 10240 * 10240 * 2, //in bytes
what are the first second and third parts? can I just change the first or should I edit all 3?

**Comment by panosnethood** [comment]
Based on my moderate programming skills this is just to help you calculate the correct size of the image in bytes but I guess you could replace everything with a single number. For example, if you want the maximum size to be 10GB, I would just put there the number 10000000000 :-)

**Comment by deckspace** [comment]
how many? 10MB is 10240 kilobytes and 10485760 bytes anyway perhaps it should be in the interface as a slider!
http://www.whatsabyte.com/P1/byteconverter.htm

**Comment by haniavis** [comment]
This is the max size of the uploaded images in bytes, as it is already stated.

For now, you can replace these with any number.

It will be integrated in the admin GUI of the GuestBook.
