### ISSUE TITLE
toolbox guides

### ISSUE THREAD

**Issue by deckspace** [mazi-project/mazi-board#7]
It's very useful having documentation in the admin section. Will there be a similar guide for the applications on the public side of the portal?

**Comment by panosnethood** [comment]
yes, the relevant parts of the admin documentation will be replicated at the public side of the portal and also made available online. We are thinking to place the "master" documentation in the wiki of the guides repository, https://github.com/mazi-project/guides, which is now hosting only the detailed installation guides. 

And then issues on documentation should be then added in that repository. (this is the repository of the mazi-board aka Guestbook application, which has also its own documentation being edited on the corresponding wiki: https://github.com/mazi-project/mazi-board/wiki
