### ISSUE TITLE
time mismatch

### ISSUE THREAD

**Issue by deckspace** [mazi-project/mazi-board#9]
I set the time/date from the dashboard and opened the guestbook then added a message which reported 2 hours ago.. sounds like difference between London and Volos!

**Comment by mgaved** [comment]
check /etc/timezone (sudo nano /etc/timezone) - just checked mine and I note "Europe/Athens".

There's a thread discussing it here: https://www.raspberrypi.org/forums/viewtopic.php?t=4977&f=5

Advice welcomed from the Guestbook administrators on the best command line code to invoke, that thread had a few different suggestions.

Suggestion: perhaps in future versions of the general MAZItoolkit there could be a timezone edit function in the time/date dashboard tool?

**Comment by haniavis** [comment]
Yes the timezone edit button should be added together with the time edit button in the MAZI portal
